config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :new, :show, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  resources :movies, only: [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, presence: true, length: {minimum: 6}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def  index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)

    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1578674473215-9e07ee2e577d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ4fHxtb3ZpZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  <div class="container">
  </div>
</div>

<div class="new-lists">
  <div class="new-list">
    <h1>Create a new <strong>bookmark</strong> !</h1>
    <%= simple_form_for [ @list, @bookmark ] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,400;0,700;1,100;1,400;1,700&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_list.html.erb
<div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
  <h2><strong><%= link_to list.name, list_path(list) %></strong></h2>
</div>

app/views/lists/index.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2250&q=80)">
  <div class="container">
    <h1>Save any kind of <strong>movie</strong> !</h1>
    <p>
      <span id="banner-typed-text"></span>
      <%= link_to 'Create a new list', new_list_path(@list) %>
    </p>
  </div>
</div>

<div class="container-list">
  <div class="list-text">
    <h3>My Lists</h3>
    <%= link_to 'Create a new list', new_list_path(@list), class: "btn btn-success" %>
  </div>

  <div class="lists">
    <% @lists.each do |list| %>
      <%= render '/lists/list', list: list %>
    <% end %>
  </div>


</div>

app/views/lists/list.html.erb
<div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
  <h2><strong><%= link_to list.name, list_path(list) %></strong></h2>
</div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1578674473215-9e07ee2e577d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ4fHxtb3ZpZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  <div class="container">
  </div>
</div>

<div class="new-lists">
  <div class="new-list">
    <h1>Create a new <strong>list</strong> !</h1>
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Submit", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner-list" style="background-image: url('<%= cl_image_path(@list.photo.key) if @list.photo.attached? %>')">
<h3><%= @list.name %></h3>
<%= link_to 'Add a movie', new_movie_path(@movie), class: "btn btn-success"  %>
</div>


<div class="movie-cards">
  <div class="list-text">
    <h3>My Bookmarks</h3>
    <%= link_to 'Create a bookmark', new_list_bookmark_path(@list), class: "btn btn-success"  %>
  </div>
  <div class="movie-card">
      <% @bookmarks.each do |bookmark| %>
        <div class="list-group-item">
          <%= image_tag bookmark.movie.poster_url, class:"poster-img" %>
          <div class="movie-card-text">
            <h4><strong><%= bookmark.movie.title %> • <%= bookmark.movie.rating %><i class="fas fa-star star-yellow"></i></strong></h4>
            <p><%= bookmark.movie.overview %></p>
            <h4><em>"<%= bookmark.comment %>"</em></h4>

            <div class="show-delete">
              <%= link_to "See more", movie_path(bookmark.movie) %>
              <%= link_to "Delete",
                            bookmark_path(bookmark),
                            method: :delete,
                            data: { confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
  <%= button_to "Delete list",
                        list_path(@list),
                        method: :delete,
                        data: { confirm: "Are you sure?" }, class: "btn btn-success" %>
</div>

app/views/movies/edit.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1578674473215-9e07ee2e577d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ4fHxtb3ZpZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  <div class="container">
  </div>
</div>

<div class="new-lists">
  <div class="new-list">
    <h1>Edit the <strong>movie</strong> !</h1>
    <%= simple_form_for [ @movie ] do |f| %>
      <%= f.input :title %>
      <%= f.input :overview %>
      <%= f.input :rating %>
      <%= f.input :poster_url %>
      <%= f.submit "Submit", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="banner-list" style="background-image: url(https://images.unsplash.com/photo-1578674473215-9e07ee2e577d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ4fHxtb3ZpZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
<%= link_to 'Add a movie', new_movie_path(@movie), class: "btn btn-success"  %>
</div>


<div class="movie-cards">
  <div class="list-text">
    <h3>My Movies</h3>
  </div>

  <div class="movie-card">
        <% @movies.each do |movie| %>
          <div class="list-group-item">
          <%= image_tag movie.poster_url, class:"poster-img" %>
            <div class="movie-card-text">
              <h4><strong><%= movie.title %> • <%= movie.rating %><i class="fas fa-star star-yellow"></i></strong></h4>
              <p class="overflow-ellipsis"><%= movie.overview %></p>
              <div class="show-delete">
                <%= link_to "See more", movie_path(movie) %>
                <%= link_to "Delete",
                              movie_path(movie),
                              method: :delete,
                              data: { confirm: "Are you sure?" } %>
              </div>
            </div>
          </div>
        <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1578674473215-9e07ee2e577d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTQ4fHxtb3ZpZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  <div class="container">
  </div>
</div>

<div class="new-lists">
  <div class="new-list">
    <h1>Create a new <strong>movie</strong> !</h1>
    <%= simple_form_for [ @movie ] do |f| %>
      <%= f.input :title %>
      <%= f.input :overview %>
      <%= f.input :rating %>
      <%= f.input :poster_url %>
      <%= f.submit "Submit", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="banner-list" style="background-image: url('https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGNpbmVtYXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60')">
<h1><%= @movie.title %></h1>
<%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-success"  %>
</div>

<div class="card-show-movie">
  <%= image_tag @movie.poster_url, class:"poster-img" %>
  <div class="card-show-movie-text">
    <h4><strong><%= @movie.title %> • <%= @movie.rating %><i class="fas fa-star star-yellow"></i></strong></h4>
    <p><%= @movie.overview %></p>
    <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-success"  %>
    <%= link_to "Delete",
      movie_path(@movie),
      method: :delete,
      data: { confirm: "Are you sure?" } %></div>
    </div>
  </div>
</div>

app/views/pages/demo.html.erb
<div class="banner" style="background-image: url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8Y2luZW1hfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60)">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <a class="btn btn-primary" href="#">Apply now</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://mpng.subpng.com/20180330/fow/kisspng-roll-film-logo-cinema-roll-5abe46881c4265.5821418815224193361158.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active nav-link">
        <%= link_to "My Movies", movies_path %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'My lists', root_path %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'New list', new_list_path(@list) %>
      </li>

    </ul>
  </div>
</div>